name: google_maps_markerwithlabel
description: MarkerWithLabel extends the Google Maps Marker class
version: 0.1.1
homepage: https://github.com/reyerstudio/google-maps-markerwithlabel
author: Stéphane Este-Gracias <sestegra@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  google_maps: ^3.2.4
  js_wrapping: ^0.4.8

dev_dependencies:
  build_runner: ^0.9.1
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  html: ^0.13.3+1
  js_wrapping_generator: ^0.4.8
  source_gen: ^0.8.3
  test: ^1.2.0

#dependency_overrides:
#  js_wrapping:
#    path: ../dart-js-wrapping2/js_wrapping
#  js_wrapping_generator:
#    path: ../dart-js-wrapping/js_wrapping_generator
