name: google_maps_markerwithlabel
description: MarkerWithLabel extends the Google Maps Marker class
version: 0.1.0
homepage: https://github.com/reyerstudio/google-maps-markerwithlabel
author: Stéphane Este-Gracias <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  google_maps: ^3.2.1
  js_wrapping: ^0.4.0

dev_dependencies:
  browser: ^0.10.0
  html: ^0.12.0
  js_wrapping_generator: ^0.4.0
  test: ^0.12.0
